[build]
builder = "nixpacks"

[deploy]
startCommand = "cd server && npm install --legacy-peer-deps && npm run build && npm start"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[env]
NODE_ENV = "production" 