services:
- type: web
  name: pdfflow-backend
  env: node
  region: oregon
  plan: free
  buildCommand: cd server && npm install && npm run build
  startCommand: cd server && npm start
  healthCheckPath: /health
  envVars:
  - key: NODE_ENV
    value: production
  - key: PORT
    fromService:
      type: web
      name: pdfflow-backend
      property: port 